### ISSUE TITLE
[vf3tb] The background of Akira stage Dural version is not dark

### ISSUE THREAD

**Issue by model-123** [trzy/Supermodel#10]
The background of Akira stage Dural version is not dark

video
https://youtu.be/2z5LpbSjTcc?t=25m47s

Screenshot
![Zs8ek4W](https://user-images.githubusercontent.com/109840450/180644394-f50f2ab5-8057-43eb-ab68-f23577ca4ad1.png)

State save
[vf3tb_20220724.zip](https://github.com/trzy/Supermodel/files/9175647/vf3tb_20220724.zip)
(I couldn't use the past one, so I prepared it again.)

Use Google Translation

**Comment by dukeeeey** [comment]
fixed
