### ISSUE TITLE
[scudplus] change in brightness

### ISSUE THREAD

**Issue by model-123** [trzy/Supermodel#100]
There is a slight change in brightness that looks like a flash in the scene where the car drives away.
It looks like the real hardware doesn't have flash.

Video
https://youtu.be/iFSpmnKcQj0?si=h2wxL-ufjNFrmvKW&t=393
https://youtu.be/fMdOngI_Yds?si=hREODftSMJNV9TOo&t=27
https://youtu.be/-2_jceUyATc?si=PKaLTqDfg_CLob2E&t=37

Screenshot
![スクリーンショット 2023-11-03 005650](https://github.com/trzy/Supermodel/assets/109840450/1c29785e-1401-46ba-aeb5-777a6b8455b6)

State save
[scudplus.zip](https://github.com/trzy/Supermodel/files/13242129/scudplus.zip)

Use Google Translation

**Comment by dukeeeey** [comment]
same bug as previous one, which should be fixed (related to line of sight)
