### ISSUE TITLE
[Wayland] When in fullscren, game area is displayed on a very small rectangle on the lower-left part of the screen.

### ISSUE THREAD

**Issue by vanfanel** [trzy/Supermodel#102]
Hi there,

I have just tried Supermodel on a Wayland-based desktop environment for the first time, and I have noticed that the games are displayed on a small area of the screen when I set fullscreen on:

![supermodeler](https://github.com/trzy/Supermodel/assets/837585/c3a61353-61d7-4a4c-96f0-b8ca3f2a21bb)

This happens unless I pass `-res=1920,1080` matching my monitor physical resolution.

This does not happen using the KMS/DRM backend of SDL2, where I had run the emulator until now.
On KMS/DRM, I can use the games original resolutions of 496x384, or any other internal resolution, and that's scaled to fullscreen.

Wayland is nowadays the GNU/Linux desktop standard, with X11 being in legacy mode. SDL2 supports X11, KMS/DRM and Wayland backends.

**Comment by vanfanel** [comment]
I *guess* problem must be around https://github.com/trzy/Supermodel/blob/aecf61762e649c13298345c7973b625be379a652/Src/OSD/SDL/Main.cpp#L146 but I have been experimenting with different values for `xResPtr` and `yResPtr` without any success.

**Comment by dukeeeey** [comment]
Supermodel doesn't automatically match the screen resolution for fullscreen, you need to set the resolution you want. Although not sure why it's rendering in a corner lol

**Comment by vanfanel** [comment]
@dukeeeey Since Supermodel is an OpenGL program, and OpenGL can't render at a resolution and scale it to a different one (unless rendering to a buffer) I believe this is a non-issue. The fact that it somehow works on KMS/DRM probably means that SDL on KMS/DRM tells Supermodel that any resolution is fine, and automatically switches the GL context  to the nearest compatible one under the hood or something similar (just speculating here: funnily enough I worked on the KMS/DRM backend of SDL2 but I am not looking back at that to be sure). 

Aaaanyway, this is a non-issue I believe. Using `wlr-randr` to set any resolution I want under Wayland before running Supermodel at that resolution does the trick. As in:

```
wlr-randr --output HDMI-A-1 --custom-mode 992x768@60                                                           
./supermodel -fullscreen -res=992,768 -channels=2 daytona2.zip                                                 

```

...and that looks as spectacularly fine as expected.
Sorry for wasting your time on this one! :)
