### ISSUE TITLE
 [srally2] background is not displayed

### ISSUE THREAD

**Issue by model-123** [trzy/Supermodel#103]
If you play the game continuously and start the game immediately after the game ends, the background of the selection screen will not be displayed.
If you start the game after the attract demo starts, the background will be displayed.

Video
https://www.youtube.com/live/HSaBr8c6IKE?si=x0BukPzVphkxCOnr&t=1697

Screenshot
![スクリーンショット 2023-11-07 000510](https://github.com/trzy/Supermodel/assets/109840450/27be360f-22fe-4423-be12-8076f975f431)

State save
[srally2.zip](https://github.com/trzy/Supermodel/files/13269581/srally2.zip)

Use Google Translation

**Comment by dukeeeey** [comment]
is this a new or an old bug in supermodel?

**Comment by dukeeeey** [comment]
Hm i see what the issue it. Fog ambient is set to zero so we are making the background layer darker.

**Comment by model-123** [comment]
I checked which version
Occurs after Git revision a214c6d

No problem until Git revision 2af0787

**Comment by dukeeeey** [comment]
should be fixed now, thanks for the bug report :)
