### ISSUE TITLE
[srally2]Overlapping shadows and skid marks

### ISSUE THREAD

**Issue by model-123** [trzy/Supermodel#104]
The shadow of the car and the skid marks seem to overlap differently.

Video
https://youtu.be/XDEAWxu8cig?si=CopC691AR0g5lxHt&t=113

Screenshot
![スクリーンショット 2023-11-07 023331](https://github.com/trzy/Supermodel/assets/109840450/491586fc-b55c-4234-bd3b-144569463a6d)

State save
[srally2.zip](https://github.com/trzy/Supermodel/files/13270671/srally2.zip)

It was correct until git 3a85bd9
![スクリーンショット 2023-11-07 023708](https://github.com/trzy/Supermodel/assets/109840450/4028b546-f1f3-4cbc-8024-0488f283b219)

Use Google Translation

**Comment by dukeeeey** [comment]
thanks I'll check it out
I know that the skid marks and the shadow of the car has the layered attribute set. I think according to the real3d dev manual that zwrites should be disabled for these polygons. Before we were doing a stencil operation, which while looked correct I am not 100% sure that was the correct implementation. We are also using the stencil function for the line of sight test.

**Comment by dukeeeey** [comment]
should be fixed
