### ISSUE TITLE
[scud] Car crystals blink during attract demo

### ISSUE THREAD

**Issue by vanfanel** [trzy/Supermodel#106]
Hello there,

I found a noticeable graphics glitch during the Scud Race attract demo: car crystals seem to blink repeatedly sometimes.
It happens, for example, during the first demo, when the second hi-score table appears.

I have recorded a video so it can easily be seen:

https://github.com/trzy/Supermodel/assets/837585/432c69ca-735e-49d1-bdf7-571dd796c00f

It can be seen

**Comment by dukeeeey** [comment]
it's the same on the original hardware

**Comment by vanfanel** [comment]
Oops, sorry! Closing this. Sorry for wasting your time.
