### ISSUE TITLE
[Linux] Supermodel now fails to compile

### ISSUE THREAD

**Issue by Shoegzer** [trzy/Supermodel#119]
Supermodel now fails to compile in linux, and it compiled without issue from master only a few days ago.  

The following information is thrown to the build log:
```
obj/m68kopnz.c:684:24: error: ‘s’ undeclared (first use in this function)
  684 |         uint res = 0 - src;
      |                        ^
obj/m68kopnz.c:684:24: note: each undeclared identifier is reported only once for each function it appears in
obj/m68kopnz.c:684: error: expected ‘,’ or ‘;’ before ‘)’ token
  684 |         uint res = 0 - src;
      | 
obj/m68kopnz.c:685:3: error: ‘ea_dst’ undeclared (first use in this function)
  685 | 
      |   ^     
obj/m68kopnz.c: At top level:
obj/m68kopnz.c:691:9: warning: data definition has no type or storage class
  691 |         m68ki_write_32(ea, FLAG_Z);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
obj/m68kopnz.c:691:9: warning: type defaults to ‘int’ in declaration of ‘m68ki_exception_illegal’ [-Wimplicit-int]
obj/m68kopnz.c:691:9: error: conflicting types for ‘m68ki_exception_illegal’; have ‘int()’
In file included from obj/m68kopnz.c:1:
Src/CPU/68K/Musashi/m68kcpu.h:1818:13: note: previous definition of ‘m68ki_exception_illegal’ with type ‘void(void)’
 1818 | INLINE void m68ki_exception_illegal(void)
      |             ^~~~~~~~~~~~~~~~~~~~~~~
obj/m68kopnz.c:692:1: error: expected identifier or ‘(’ before ‘}’ token
  692 | }
      | ^
```

Test information:
* OS: Linux Mint 21.2 / kernel 6.2
* CPU: Intel i7-10870H
* Compiler: gcc-12.3.0
* Bad build: a19ba3cba80a352f4103551b90633c9d05f60d22
* Last known good build: 391e1b962293576fb4e1f9fcaf17afc640ad0d10
* Log: [build.log](https://github.com/trzy/Supermodel/files/13539875/build.log)

**Comment by ToBul** [comment]
Did you compile with the  -j  switch? 
Try a fresh recompile without it.
A while back gcc hit  a problem where it would run wild with -j.  Somewhere around  version 12 IIRC.
That's when I stopped using that switch.

FWIW
It's compiling ok for me in a slightly old version of Ubuntu and Manjaro.
Also ok in latest MSYS.

**Comment by trzy** [comment]
Just tried it on gcc 13.2.0 in Windows, no problems there. I think ToBul may be correct: parallel builds with -j can get screwed up. I'm not sure why. To me, the Musashi build rules look correctly specified.

**Comment by Shoegzer** [comment]
Thanks guys, good advice.  It's compiling for me after trying again here too, so I'll close this.  I am indeed building with -j9 on an 8-core, 16-thread CPU.  I too had intermittent issues compiling supermodel with -j several years ago, though suddenly it stopped, I presume due to some specific commit.  At least the blessing here is that we have a very narrow set of commits that seem to cause it to happen again, if that helps to trace the issue and resolve it once and for all, to avoid frivolous issue reports like this one in the future.  On the other hand it may not be worth the effort.

**Comment by trzy** [comment]
It's not the commits. It's the Makefile that's the problem. The Musashi 68K core includes a build step where an intermediate program has to be compiled and then used to generate the source code. I think the problem is that make is computing dependencies incorrectly and compiling before all files are ready.
