### ISSUE TITLE
[srally2] Unwanted objects

### ISSUE THREAD

**Issue by model-123** [trzy/Supermodel#12]
If you play the championship repeatedly, there are unnecessary objects at the starting point

video
https://youtu.be/XVeRFZ6tExQ?t=5862

Screenshot
![ss 2022-07-25 193000](https://user-images.githubusercontent.com/109840450/180763993-afebbdbc-eb8f-4581-867f-6efec44b8bd7.png)

State save
[srally2_20220725.zip](https://github.com/trzy/Supermodel/files/9180561/srally2_20220725.zip)

Use Google Translation

**Comment by dukeeeey** [comment]
Does this still happen? Can someone test this?

**Comment by ToBul** [comment]
Still happens.
It seems the later levels produce junk/extra data that show up when going back to the earlier levels.

Easiest way to reproduce,
Play in Practise mode and chose Snowy level, then just let the 60 second timer run down to end the game.
Now play another practise game in either Desert or Mountain and you'll see objects/textures at the sides of the start line.
Spin the car around to take a good look.

If you play Riviera then go back to Desert or Mountain, you'll see a flickering poly along the finishing line.
If you park the car on the poly the flickering will stop after about 1 second until you move again.

**Comment by model-123** [comment]
Objects that are not yet needed will be drawn
[srally2.zip](https://github.com/trzy/Supermodel/files/13256900/srally2.zip)

![スクリーンショット 2023-11-04 233157](https://github.com/trzy/Supermodel/assets/109840450/3362755e-e1e1-4f3b-b5c3-5c32ff3beb46)

**Comment by dukeeeey** [comment]
This definitely doesn't happen on the original hardware?
The polygons don't look totally out of place there.

**Comment by ToBul** [comment]
> This definitely doesn't happen on the original hardware? 

Don't think so.

In the video above the guys have multiple runs often hitting the latter levels.
When they cross the line on the early levels on their next run, you never see any artefacts.
If you do the same in Supermodel, you see the objects as seen in model 123 last photo.

I wonder if the Games.xml patch is interfering, in which case we're probably stuck with it?

**Comment by dukeeeey** [comment]
should be fixed :)
