### ISSUE TITLE
[vf3tb] Character selection line when increasing resolution

### ISSUE THREAD

**Issue by model-123** [trzy/Supermodel#123]
Lines are displayed in the character selection of vf3tb (vf3) only when the resolution is increased.

When I asked Ian a long time ago, he said it was probably an artifact of expansion.
I hope it gets fixed.

## Video
https://www.youtube.com/live/ygkLOvKlESU?si=77yCbrj9Qk71Fpsk&t=3342

## Screenshot
![スクリーンショット 2023-12-23 043144](https://github.com/trzy/Supermodel/assets/109840450/89f20445-2eae-464c-b92e-6569cda1dc04)

## State save
[vf3tb.zip](https://github.com/trzy/Supermodel/files/13756468/vf3tb.zip)

Use Google Translation

**Comment by dukeeeey** [comment]
It's simply a resizing artefact. When there is a 1:1 mapping between the texture and the screen everything works as expected. When you resize the bilinear texture filtering kicks in and samples some of the adjacent pixels, which in this case is black, outside the area you want. It's not really fixable as it's just how the texture filtering works.

**Comment by model-123** [comment]
Thank you again for the detailed explanation
