### ISSUE TITLE
Native support for cheats in mame XML format

### ISSUE THREAD

**Issue by eadmaster** [trzy/Supermodel#125]
Better than using an external cheat tool like ArtMoney:
https://github.com/john-peterson/bin-patch/wiki

**Comment by trzy** [comment]
I'm not sure what that repo is? As for cheat tool support, how would the interface look? Supermodel has a debugger that could be augmented with features to find memory regions to patch and applying patches from the config would be easy but support for dynamically activating cheats at run-time would probably require a GUI, which Supermodel lacks.

**Comment by eadmaster** [comment]
i understand, this makes more sense as a frontend request.

**Comment by roioros** [comment]
It would be great if it could be added to the GUI and have support for cheats.
