### ISSUE TITLE
Raspberry Pi 5: GLSL 4.10 is not supported. 

### ISSUE THREAD

**Issue by TotalCoolness** [trzy/Supermodel#127]
I compliled it on the Raspberry Pi 5 but I get this error with scud racer:

error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
    Title:          Scud Race (Australia, Twin/DX)
    ROM Set:        scudau
    Developer:      Sega
    Year:           1996
    Stepping:       1.5
    Extra Hardware: Digital Sound Board (Type DSB1), Drive Board, Net Board

0:3(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

**Comment by trzy** [comment]
Known issue. See: #87 #105 
The default, accurate engine requires OpenGL 4.1 and the Pi doesn't support that.
You can run the legacy engine (-legacy3d), which works with GL 2.1. However it hasn't been updated in years and is far less accurate. Should still be ok for the popular titles.

**Comment by dukeeeey** [comment]
The tilegen uses opengl 4.1 too so it won't work. I'm gonna look into porting the triangle renderer to opengles

**Comment by TotalCoolness** [comment]
This guy got it working on the older pi 4.  But its an old video. The settings have changed. 

https://youtu.be/0p8hlh4mUyw?si=PkT0IQa3FJh8Q7v3
