### ISSUE TITLE
Black/Blue Flashes

### ISSUE THREAD

**Issue by MrShooter42** [trzy/Supermodel#132]
No slowdown, but constant black flashes seemingly at random making the game unplayable.

**Comment by MrShooter42** [comment]
This happens in Daytona USA 2 PE and Virtual On 2.

**Comment by MrShooter42** [comment]
This seems to occur less in earlier versions. One black flash in Supermodel Version 0.3a-git-c40d6ac as compared to constant blackouts in the latest version.

**Comment by dukeeeey** [comment]
Linux? What gpu

**Comment by MrShooter42** [comment]
Windows 11, GTX 1070

**Comment by dukeeeey** [comment]
Does it flash if you pause the game, alt + p

**Comment by MrShooter42** [comment]
Yes, if I time it right, it flashes. It is black more often than not.

**Comment by MrShooter42** [comment]
I can't seem to pinpoint the cause. Starting to stream the game on discord fixed it for a single level when I was playing Virtual On 2, then it came back only to stop after I ended the stream. It eventually returned again in the attract mode.

**Comment by MrShooter42** [comment]
I figured it out!  This issue is directly tied to the PowerPC frequency. When set to the default 60 mhz, it has the flashes. At the arcade setting of 166 mhz, it stops! 100 MHZ has flashes as well, but much less.

**Comment by trzy** [comment]
Ok. I need to fix this issue once and for all. The PowerPC frequency should be hard-coded to the appropriate one given the stepping (66, 100, or 166). -ppc-frequency should become an override that by default is not set at all. I'll make the change soon.

**Comment by trzy** [comment]
Fixed in the latest commit! Everyone should remove PowerPCFrequency from their config files.
