### ISSUE TITLE
Request: Appimage binary

### ISSUE THREAD

**Issue by PhoenixBlade24** [trzy/Supermodel#145]
I would like to request an Appimage binary with a rudimentary GUI included. For various reasons, using this emulator is difficult on Linux-based systems and I have been having a lot of trouble getting it to run, both through the AUR and via the Flatpak. An Appimage would contain everything the Supermodel emulator needs to run in a single, portable binary which would allow it to be used across all Linux distributions with little issue. A GUI would also allow players to select the rom they would like to load with ease.

**Comment by jaoxford** [comment]
There's a supermodel GUI program floating around somewhere but it's quite trash.

I'd recommend using launchbox as your GUI / front-end.

**Comment by trzy** [comment]
I eventually would like to have an integrated GUI, something similar to MAME's (that is, in-emulator that also works in fullscreen mode) but this is not currently planned.
