### ISSUE TITLE
Enable scuddxo commit has broken some 1.5 step games?

### ISSUE THREAD

**Issue by ToBul** [trzy/Supermodel#148]
I might be doing something wrong but has the new register logic broken some of the other 1.5 step games?
When building from source, I'm getting "Write to invalid 53C810 register" with le mans, lost world games and all scuds except scuddxo.

**Comment by gm-matthew** [comment]
My recent update to get the newly dumped version of Scud Race (scuddxo) working seems to have broken most of the other step 1.5 games; will try to fix ASAP
