### ISSUE TITLE
Lost world and La machine gun graphics bug

### ISSUE THREAD

**Issue by Garagefreek** [trzy/Supermodel#163]
The T-rex leg is not completely gone yet in the lost world intro and La machine guns transitional effect is buggy after the select stage screen it's supposed to change to black for a quick second but on the emulator it goes to static white instead?

**Comment by gm-matthew** [comment]
What resolution are you running, and do you have widescreen enabled? For me the T-rex leg does not show up if I run Supermodel with a 4:3 resolution, but it does show up briefly if I run with a 16:9 resolution, regardless of whether widescreen is enabled or not:

![image](https://github.com/user-attachments/assets/66258a65-edaa-4ffb-b3bf-f8948f435e98)
![image](https://github.com/user-attachments/assets/9a21af22-f2fb-45fa-8107-8a25984bdf28)

**Comment by Garagefreek** [comment]
I’m running it on a 4:3 aspect ratio with a resolution of 1920 x 1080 with optimal settings on the most current supermodel gui..what do you suggest?

**Comment by gm-matthew** [comment]
Try setting the resolution to 1440x1080.

**Comment by Garagefreek** [comment]
I'll give it a go thank you.

**Comment by Garagefreek** [comment]
How you doing I tried it on 1440x1080 it produced the same result but works fine on 1280x1024 or below that on any one..

**Comment by gm-matthew** [comment]
The next update should fix it so that the T-rex leg doesn't show up unless widescreen is explicitly enabled

**Comment by Garagefreek** [comment]
Thank you..will LA machine be an easy fix?

**Comment by Garagefreek** [comment]
Cool, will it be an easy fix for la machine guns?

**Comment by Garagefreek** [comment]
Cool, is LA machine gun going to be an easy fix?
