### ISSUE TITLE
Sega Bass Fishing (Upright) - getbassur - graphical issues

### ISSUE THREAD

**Issue by cor094** [trzy/Supermodel#166]
Introduced in Git revision ee5d652 (2024-07-05) built for 64-bit Windows, I have some graphical issues with Sega Bass Fishing. The fish in casting view show up as rectangles, instead of usual fish shape. This does not appear in versions prior to ee5d652, but occurs in this version all versions after. Most recent at time of testing 5fa402f (2024-07-19)/
![Capturez](https://github.com/user-attachments/assets/5bbbaa88-71f8-4e58-8d4b-e02e4b3b8b93)

**Comment by dukeeeey** [comment]
Yeah unfortunately I think our mipmapping code is not quite correct. If we can't find an adequate solution I might roll back the code.

**Comment by gm-matthew** [comment]
I've come up with a fix that makes the fish look like fish again, just waiting for it to be merged

**Comment by cor094** [comment]
That's awesome, thank you!

**Comment by gm-matthew** [comment]
With the latest update this issue has been resolved, the fish are fish-shaped again

![image](https://github.com/user-attachments/assets/61706d67-b11b-4df7-8bf9-0ec92524ce0c)
