### ISSUE TITLE
Scud Race Sunglare 

### ISSUE THREAD

**Issue by Riddler1** [trzy/Supermodel#176]
Hi Team, 

Not since Supermodel 0.2a (24th Sep 2011) has the sunglare/sunspots looked as good as it used too.

Compared to 0.2a, the most recent release (dd90d0e), the sunglare passes through the car as a black ring and lacks the colour the old version had.  

can it ever be the same again? 🤞

Supermodel 0.2a (Sep 2011)
![Screenshot_20240802-234819_Gallery](https://github.com/user-attachments/assets/8075d915-f804-4460-90d8-3b7cac08a76f)

Latest version dd09d0e (Aug 2024)
![Screenshot_20240802-234846_Gallery](https://github.com/user-attachments/assets/943dc555-e6cd-4459-80ee-3b6ac543268a)

**Comment by gm-matthew** [comment]
The same thing happens on real hardware:

![image](https://github.com/user-attachments/assets/d3ed4216-44a5-49a6-a5d7-cf54dfa24bac)

Source: https://www.youtube.com/live/qFUUnD0cWCM

Model 3 achieves translucency not by alpha blending like modern GPUs do, but by drawing every other pixel in a stipple pattern and then using blending the pixels together in post-processing. The lens flare is being drawn over the same pixels as the rear window so the former effectively erases the latter.

Although the method in 0.2a (which is still used in the legacy engine) looks better in this particular case, it causes problems in other cases so we will not be reverting back to it.

**Comment by Riddler1** [comment]
Fantastic, i'm happy with that. Thank You!
