### ISSUE TITLE
[Regression] Video appears in lower-left corner only

### ISSUE THREAD

**Issue by Shoegzer** [trzy/Supermodel#177]
Video now appears in lower-left corner of the screen only, whereas before it properly filled the screen.

Bad commit observed: dd90d0e2e0ae2a8f05f16f1780d30d7d58f87f5d
Last known good commit: 49ca8c148070a958bf60b9ca983c9de607131bd0

Options used:
-force-feedback -res=1024,768 -vsync -fullscreen -quad-rendering

* OS: Linux Mint 22 / kernel 6.8
* GPU: NVidia GTX 3070 / driver 535.183

**Comment by gm-matthew** [comment]
That's weird, because we haven't made any changes since 49ca8c1 that should affect video output. I tried running Supermodel with the same options, albeit running Windows 10 instead of Linux, and I was unable to recreate the problem.

I assume that you're compiling Supermodel yourself, are you sure that you are compiling both commits with the same options?

**Comment by Shoegzer** [comment]
@gm-matthew yeah I thought it wa strange too.  I'm building the project myself with `gcc-14.0.1`.

Build options are the same before and after these commits: `make -j9 -f Makefiles/Makefile.UNIX NET_BOARD=1`

**Comment by Shoegzer** [comment]
Another point to add, I'm using the following runtime options:

`-force-feedback -res=1024,768 -vsync -fullscreen -quad-rendering`

I've tried removing -res and -vsync but I still get the issue.  I'm not sure if anything else would help.

I need to also mention: this occurs on a notebook hooked up to  an external monitor.  If I launch supermodel on the notebook screen, the video appears as it should.  So I'm guessing it's due to some kind of frequency issue with the monitor?  That said, again this wasn't occurring until the commit noted above, but as you said I'm not sure why it would matter.

I'm fine with closing this issue if you think it's beyond the scope of this project, but I'm at least curious on any thoughts you or others may have.

**Comment by dukeeeey** [comment]
the issue is probably to do with multiple monitors, supermodel doesn't really have built in support for multi screen setups

**Comment by Shoegzer** [comment]
That's fair.  I do have another monitor setup which is an arcade CRT though, it would be ideal for the project to support these kinds of setups as part of its presumed goal, though I'm sure there are other priorities.  

That said, I don't want to beleaguer the point - I'm fine closing this if you think it's for the best.  If you ever need help testing code that aims to tackle this in the future though, I'm happy to help.
