### ISSUE TITLE
arm 64 android version? (suggestion)

### ISSUE THREAD

**Issue by tails101** [trzy/Supermodel#183]
supermodel have an arm 64 version on linux.
it just integrated retropie, batocera and recalbox already include a version for arm 64 as well and those are linux distro.
is it possible to have an android version derived from those linux arm ones please?
since android use a linux kernel.
that would be very nice and i am sure it will be popular.

**Comment by trzy** [comment]
Not planned, UI is out of scope for now. This is a project for a contributor or for a fork.
