### ISSUE TITLE
Gamma

### ISSUE THREAD

**Issue by toxieainc** [trzy/Supermodel#189]
Hi!

This is not so much an issue, but more like a question, or comment on the rendering pipeline:
As e.g. the Virtua Racing port on the Switch stumbled over this, i wonder how gamma correction is being done in Supermodel.
In VR, there was initially an issue where the gamma was not compensated for the ArcadeCRT<->LCD gamma differences, thus colors were very off. They patched this later on and offered a gamma slider (not the best solution, but better than ignoring it).

So how is this done in Supermodel? Cause maybe that could help to further improve visual fidelity/precision, depending on how/if the gamma compensation is currently done implicitly during rendering itself, instead of a postprocess (which then affects the final pixels instead of parts that are still composited, etc).

**Comment by dukeeeey** [comment]
There is no gamma correction. I know the original real3d pro-1000 had gamma correction functionality, but as far as we know it's not used on the model 3. I assume image we draw if rendered on an original screen would look the same, there for if you wanted to emulate a CRT you would need some sort of post process filter.

**Comment by toxieainc** [comment]
Okay, this is what i would have assumed as well.
So basically all lighting/material computations are done in whatever the textures/color-parameters color space are in, and then that is as-is composited and blitted to the screen.
That means that (in theory) one should at least compensate for the CRT vs LCD gamma difference in an optional(!) pass.
I will experiment with that then, thanks!

**Comment by toxieainc** [comment]
Do you guys know which monitors were used in the Model 3 machines?

From my experiments so far, using a color profile that matches common/higher-end japanese CRTs of the time, i think i get closer to the colors that can be seen on youtube vids (e.g. the roads in Daytona 2 seem to be more blue in the videos).

**Comment by trzy** [comment]
Unfortunately I don’t. I don’t think anyone ever produced a good description of the non-PCB components :(Sent from my iPhoneOn Sep 16, 2024, at 2:09 AM, toxie ***@***.***> wrote:﻿
Do you guys know which monitors were used in the Model 3 machines?
From my experiments so far, using a color profile that matches common/higher-end japanese CRTs of the time, i think i get closer to the colors that can be seen on youtube vids (e.g. the roads in Daytona 2 seem to be more blue in the videos).

**Comment by p1pkin** [comment]
> Do you guys know which monitors were used in the Model 3 machines?
> 
> From my experiments so far, using a color profile that matches common/higher-end japanese CRTs of the time, i think i get closer to the colors that can be seen on youtube vids (e.g. the roads in Daytona 2 seem to be more blue in the videos).

Check Sega Model 3 games service manuals, there was listed specific monitors.
iirc popular models was Nanao MS9, Sanwa PM1745 and others
https://wiki.arcadeotaku.com/w/User:Theretrobristolian/MS9-29
all of them is special "middle resolution" monitors, which supports 24kHz rate unique to arcade devices, and not really similar to "common/higher-end japanese CRTs of the time"

**Comment by toxieainc** [comment]
Thanks a lot, that should give me some more hints on what to search for nextcurve .
With 'common japanese' i meant more the color space the CRT is able/designed to display. So that may still match up.
For what i have in mind, its just about gamma/EOTF and color space, not all the other factors of a CRT.

**Comment by toxieainc** [comment]
So far, it seems to confirm that the color temperature was really VERY blueish/'cold', even more so than the D93 space i already tried.

**Comment by p1pkin** [comment]
> With 'common japanese' i meant more the color space the CRT is able/designed to display. So that may still match up.

no, it should not, and highly depends on specific device settings, age and condition.

**Comment by toxieainc** [comment]
Absolutely. But different color spaces and quirks of (regional) CRTs are a thing that can(!) be considered.

So if you try to emulate a 'new'/factory-default arcade/CRT monitor on a sRGB-capable monitor, then there is math/measurements to do this nowadays. I understand that this is entering a region where things get debatable what is 'more correct' (and what about all the CRT adjustment knobs, etc), but a lot of emulators offer things like that nowadays, so why not have the option to do it? And so far my experiments make the image look more like what i find on youtube vids of the actual arcade machines.

**Comment by toxieainc** [comment]
A very good example that i found is actually Sega Rally 2. The Sega logo then looks much more like one is used to, and the sky during gameplay becomes the blueblue sky we all love from Sega.  ;)
