### ISSUE TITLE
Make quad rendering the new default?

### ISSUE THREAD

**Issue by toxieainc** [trzy/Supermodel#19]
As the feature is more precise and roughly same speed (measured on my Intel and NVIDIA laptop GPUs, using HDish resolution and no-throttle and no-vsync), should it be the new default?

**Comment by dukeeeey** [comment]
The quad renderer work on apple. Also needs a compatibility profile which is also unsupported by apple. No idea how it performs on amd hw

**Comment by trzy** [comment]
We could make it default on Windows and Linux (anything not Apple) with an ifdef. We don’t want too many of those floating around the code base but in this case it’s probably fine.

**Comment by toxieainc** [comment]
I think its a good idea! :)

**Comment by dukeeeey** [comment]
I would like this as the default but I think AMD users will cry :p

**Comment by toxieainc** [comment]
But why? Do you know of AMD users that complained about the quad rendering performance with the new changes?
Even Intel now is roughly same speed as the tri pipeline.

**Comment by dukeeeey** [comment]
I think it's just the geometry shader that helps nuke the performance. Geometry shader is usually fast on intel because it's all done on the cpu. There is no round trip.
