### ISSUE TITLE
Sega rally 2 desert stage bug.

### ISSUE THREAD

**Issue by Garagefreek** [trzy/Supermodel#199]
The beginning of the race there’s a black vertical line in the centre of the screen then disappears when you start driving?

**Comment by gm-matthew** [comment]
I haven't observed this myself, could you provide a screenshot?

**Comment by Garagefreek** [comment]
![Screenshot 2024-10-02 010537](https://github.com/user-attachments/assets/3a6d37b5-5d21-4361-bc25-e0657acac790)

**Comment by Garagefreek** [comment]
That line as far as i know only shows up on a 1920x1080 display setting only??
