### ISSUE TITLE
Transparency Issues in all games

### ISSUE THREAD

**Issue by RetroPCYT** [trzy/Supermodel#20]
I was testing the lastest Supermodel 3 version (0.3a-git-0eef09b_Win64) and notice issues with the transparency. Its more noticeable in the reflections/lens flare effects in games like "Sega Rally 2" or "Scud Race"... this glitch reminds me a lot of when you try to emulate Dreamcast without using OIT, is this similar layer issue?

Sega Rally 2:
![sega rally 2](https://user-images.githubusercontent.com/99839803/186538604-91426a0e-aa31-49da-ae46-6abb3ca99870.png)
![sega rally 2 (1)](https://user-images.githubusercontent.com/99839803/186538606-bc275798-e404-49c8-aed8-d24ef63dead4.png)

Scud Race:
![scud race](https://user-images.githubusercontent.com/99839803/186538607-0d47bec3-3edb-4273-8482-f0177abda787.png)
![scud race (1)](https://user-images.githubusercontent.com/99839803/186538609-babd95fe-1e44-4f7d-8ffe-4ecc92d5e0ea.png)

Core i7 4770K
GTX1070
Windows 10.

Saludos!

**Comment by dukeeeey** [comment]
Compare it against the original arcade h/w

**Comment by toxieainc** [comment]
Check for example https://youtu.be/jRvpKZ1mPH8?t=30 or https://youtu.be/jRvpKZ1mPH8?t=48
Artifacts look similar to me.

**Comment by trzy** [comment]
Closing issue because we concur these artifacts are authentic.

**Comment by trzy** [comment]
Model 3 did not have OIT and I believe all of these are correct behavior.
When reporting suspected graphics glitches, please provide a comparison to
the real hardware. For example, look at the replay at the end of this
video: https://www.youtube.com/watch?v=fBI1XWlIpeM

Seems to me these artifacts occur on actual hardware and are therefore
*desirable* behavior in an emulator focused on accuracy first :)
