### ISSUE TITLE
GCC build now broken 

### ISSUE THREAD

**Issue by ToBul** [trzy/Supermodel#204]
gcc is complaining that NewConfig.cpp is missing the iterator header

![log](https://github.com/user-attachments/assets/7e1af521-8132-4072-a3ff-21c7a994c0e0)

**Comment by dukeeeey** [comment]
thx i'll fix it

**Comment by dukeeeey** [comment]
can you check it builds for you now?

**Comment by ToBul** [comment]
Yes. all good.
