### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by toxieainc** [trzy/Supermodel#206]
Starting with 905bfa2 (8e7b850 still worked as before), it seems like the scaling of the framebuffer is handled differently, although there is no explanation of why this happened suddenly (i didn't see anything fishy in the commits), e.g. when running
supermodel -res=1920,1080 srally2.zip

Another uninitialized var problem?

**Comment by dukeeeey** [comment]
hm I can't replicate this.
What settings? AA? Does it happen in windowed mode? GPU ?

**Comment by toxieainc** [comment]
Just the raw command line above, default ini file, so windowed mode.

**Comment by dukeeeey** [comment]
What windows dpi

**Comment by toxieainc** [comment]
No clue, 125% scaling.

**Comment by toxieainc** [comment]
But that is the same in both tests, so should not matter, right? Or was some build config changed in that range?

**Comment by dukeeeey** [comment]
I *think* dpi can change the size of the window you render to. So maybe this is the issue. Try 100% scaling

**Comment by toxieainc** [comment]
Will try, still confusing if that would be the cause though, unless the build setup changed/tools were updated, otherwise all should react the same, right?

**Comment by dukeeeey** [comment]
![image](https://github.com/user-attachments/assets/55c11407-67b6-45a3-a8be-26ae37705938)
what mine looks like?

**Comment by toxieainc** [comment]
and without wide screen?

**Comment by toxieainc** [comment]
https://github.com/trzy/Supermodel/commit/8e7b8506ff0c0f2b0ed994205e4108bc387fab16: ![grafik](https://github.com/user-attachments/assets/6deea7f6-5219-4490-b11a-8f51abd45ed9)

**Comment by toxieainc** [comment]
Okay, i nailed it down now. As i have a 2GPU laptop setup (Intel CPU/GPU + NV GPU), for whatever reason the NV does the weird scale, the Intel the expected one.  :/
Why windows decided to pick 1.GPU for that build, and 2.GPU for the other (same executable name) is beyond me.

**Comment by dukeeeey** [comment]
Could be some driver option? Honestly I'm not sure

**Comment by toxieainc** [comment]
Got it. Its really related to the windows DPI. If one embeds in the executable that the app is DPI aware then it works.
Will do a PR to change the vcproj, and will try to find out how that works for gcc.

**Comment by toxieainc** [comment]
Apparently NV driver does the DPI scale, Intel not (don't know which is correct, as this is a GL windows after all).
