### ISSUE TITLE
request: merge project with MAME

### ISSUE THREAD

**Issue by thevirtualarcade** [trzy/Supermodel#207]
hi

Thanks a lot for the fantastic work on supermodel, I really enjoy it!

Maybe it would be good for the future and to attract more contributors to add this project to MAME? 

https://www.mamedev.org/

The same games are in MAME but they don't work. It would be a fantastic contribution to MAME!
I think the GPLv3 is a perfect license for this

**Comment by dukeeeey** [comment]
Mame is purely software rendering. It can't really be merged. The work from supermodel could be ported to mame if people were interested in doing it.

**Comment by dukeeeey** [comment]
The GPU emulation is very accurate to the original h/w, with the exception of the quad rendering. Quad rendering in supermodel is far superior to the original hardware, it will handle bow tie quads and all kinds of insane shapes. It also doesn't distort if you rotate the quads which is something that can happen on the model 3, depending on the shape of the quad.

Emulating it how the actual hardware works, ie drawing horizontal spans would be way easier in software (mame). Mame is plenty fast enough for cpu rasterisation at the native resolution. But I know for a fact this project exists kind of means no one in mame is bothered about working on model 3 emulation, which is a shame.

**Comment by toxieainc** [comment]
Sorry, didn't want to imply that the GPU emulation is bad or something (rather the contrary), its just that MAME nowadays does not make many compromises regarding accuracy, as it also wants to act as kind of a documentation of the original hardware where possible/feasible, so in many cases its down to the exact same bits outputted to screen or speakers (of course not everywhere yet).
