### ISSUE TITLE
le mans 24 steering problem

### ISSUE THREAD

**Issue by thevirtualarcade** [trzy/Supermodel#209]
Hi

I'm using Supermodel_0.3a-git-64a7e35_Win64 on Windows.
In the game le mans 24 steering is almost impossible. If you use the keyboard and press LEFT or RIGHT arrow once, the wheels turns all the way left or right. I think the steering is too sensitive.
I definitely not remember the game in the arcades being so sensitive to steer.

**Comment by trzy** [comment]
Digital steering doesn't really work that well in any game - these should be played ideally with a wheel or at least an analog stick. There is no bug in the Le Mans 23 steering, that is really how it behaves.
