### ISSUE TITLE
GCC build broken

### ISSUE THREAD

**Issue by ToBul** [trzy/Supermodel#210]
The math header was removed from InputSystem.cpp.
Gcc can no longer perform ceil().

![math](https://github.com/user-attachments/assets/c8efb1a9-4b50-4dcf-ad36-deda125a0aab)

![InputSystem](https://github.com/user-attachments/assets/affa7e62-e16e-4937-83de-125ffbdebac5)

**Comment by dukeeeey** [comment]
Thanks. Will fix it

**Comment by toxieainc** [comment]
Oh whoops, sorry..

**Comment by dukeeeey** [comment]
should be fixed, thanks for the report
