### ISSUE TITLE
Reduce fixed function pipeline usage

### ISSUE THREAD

**Issue by zephryn** [trzy/Supermodel#3]
It seems like only a few pieces of code in the 2D renderer and new 3D renderer (a snippet `CRender2D::DisplaySurface` and some crosshair rendering) utilize fixed function rendering. The legacy renderer might be a whole other beast-- I haven't looked into it much-- but I think it'd be interesting to adapt everything else to use shaders to help it be compatible with more OpenGL versions (e.g. Core, ES, and newer standard OpenGL versions which have these functions deprecated).

**Comment by trzy** [comment]
I'm not opposed to that but the legacy engine for now should continue to be functional. It would be nice if we didn't need to have a legacy 2D engine as well. Eventually, the legacy engine should probably be removed altogether but for now, some people are apparently still using it. 

It would also be nice to think about how we could support adding things like text rendering or other UI elements that are sorely missing.

**Comment by trzy** [comment]
Closing this issue. As mentioned above, I am open to continuing this discussion!
