### ISSUE TITLE
Ski Champ forces a 1st Person View when set to Free Play. No option to change view.

### ISSUE THREAD

**Issue by normchomsky** [trzy/Supermodel#34]
Ski Champ forces a 1st Person View when set to Free Play. No option to change view.

I cant see a view change button anywhere, not even in the Input Test.

**Comment by ToBul** [comment]
when in attract mode, press 'q', 'w' or 'e' to get to the character select screen.
q = far view
w = mid view
e = first person

I don't think the real hardware had a player 1 start button, although Supermodel will emulate one.
I don't think you can change view in game either. On the real machine, you were probably expected to choose your character and then just hang on for dear life.

**Comment by normchomsky** [comment]
ahh I see now. There was no start button on OG hardware. You'd use the colored buttons to set your view before adding credits, as adding credits auto starts the game. In the case of Free Play you simply press one of the colored buttons to start your game in that view. When using the Start button to start the game in Free Play, Supermodel simply uses Button 3/Green instead as the is no actual 'start' button.

So in essence: 
If using Credits press the colored button for the view you want before adding credits.
If using Free Play simply start the game by pressing the colored view button you want.
Button 1/Blue = Far View
Button 2/Red = Mid View
Button 3/Green = 1st Person

**Comment by ToBul** [comment]
Hold down 'q' ,'w' or 'e' if coining up.
