### ISSUE TITLE
[Linux] Build Failure

### ISSUE THREAD

**Issue by Shoegzer** [trzy/Supermodel#40]
Details:

* OS: Linux Mint 21 / kernel 5.15
* Compiler: gcc 11.3.0
* Bad build commit: e47258c61d0d5ce47330c311c8ebd03a9026a9f6
* Last good build commit: 4c727abdc84e5c9eb56b3a178c2dd473d7581725
* Build log: [build.log](https://github.com/trzy/Supermodel/files/9957669/build.log)

**Comment by dukeeeey** [comment]
should be fixed

**Comment by Shoegzer** [comment]
Thanks @dukeeeey, it is fixed.  Closing.
