### ISSUE TITLE
Linux Intel GPU error: GLSL 4.10 is not supported

### ISSUE THREAD

**Issue by unassumingbadger** [trzy/Supermodel#43]
Linux 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

Supermodel Version 0.3a-WIP as of 5f30614c4c02e3957fc1d27c02ab13664984946a

./supermodel -print-gl-info

OpenGL information:

  Vendor                   : Intel Open Source Technology Center
  Renderer                 : Mesa DRI Intel(R) HD Graphics (ILK)
  Version                  : 2.1 Mesa 20.3.5
  Shading Language Version : 1.20
  Maximum Vertex Array Size: 3000 vertices
  Maximum Texture Size     : 8192 texels
  Maximum Vertex Attributes: 16
  Maximum Vertex Uniforms  : 16384
  Maximum Texture Img Units: 16

./supermodel -legacy3d vf3.zip

0:3(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader

I'm not sure why its trying to use GLSL 4.10.

**Comment by dukeeeey** [comment]
New version needs gl 4.1 to run. Opengl 2.1 came out 16 nearly 17 years ago.

**Comment by unassumingbadger** [comment]
Is the -legacy3d option going away or does it require gl 4.1? I'll go ahead and close this out.

**Comment by dukeeeey** [comment]
Use a sightly older build of supermodel. It will run on your 2.1 hw.
