### ISSUE TITLE
[Question]   Have you tried (is it possible) to use a windows compat steering wheel with this?

### ISSUE THREAD

**Issue by Fredrum** [trzy/Supermodel#72]
Hi I just saw someone running this on an Orange Pi 5 and I'm going to try see if it works when I get some free time.
I wanted to ask if you have tried using a steering wheel controller for any of the driving games?
Maybe if its using SDL for input that could be possible?

**Comment by trzy** [comment]
I have not but many users do play with steering wheels. Supermodel supports them. I don't know about how well they would work with an Orange Pi 5 but Linux uses SDL and SDL has support for force feedback, too.
