### ISSUE TITLE
New gfx engine won't work on Orange Pi 5

### ISSUE THREAD

**Issue by Fredrum** [trzy/Supermodel#73]
Hello!! 
Thank you a million times for making your awesome emulator available for people to try! :)
I just spotted someone posting videos running it on a Orange Pi 5 so I thought I have to try it too on mine!

I just got Sega Rally 2 going to start with and it runs at mostly 60fps when using your legacy 3d engine option. Very Cool! 
There are some graphical things that seem broken (like the speedometer and doubling up flickering cars) on the old engine but I'm sure you're aware of that or it's possible that it's the 'Panfork' mesa drivers on my system that's not fully working. (The GPU does not yet have full proper Panfrost support so Armbian has been using this 'Panfork' version)

When I try with the new engine using default or explicit with -new3d it doesn't want to start at all and gives a message,

`Error: Unable to create OpenGL context: Could not create GL context: GLXBadFBConfig`

The SBC is run on Armbian with Ubuntu gnome desktop.
This is my glxinfo output if you're interested:

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Panfrost (0xffffffff)
    Device: Mali-G610 (Panfrost) (0xffffffff)
    Version: 23.0.0
    Accelerated: yes
    Video memory: 7689MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Panfrost
OpenGL renderer string: Mali-G610 (Panfrost)
OpenGL version string: 3.0 Mesa 23.0.0-devel
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 23.0.0-devel
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

Cheers and Thanks again this was fun to try!

**Comment by Fredrum** [comment]
On suggestion by a youtuber I trued using commit 4c727ab and it fixes probably all those gfx glitches under legacy3d mode. Nice.
I can also run Sega Rally 2 with the new gfx mode but like you suggest the frame rate is lower so I'll probably stick with legacy until maybe one day the Mesa drivers for the system gets updated.

**Comment by dukeeeey** [comment]
I could maybe try and port the engine to opengl ES
