### ISSUE TITLE
[eca] bright background

### ISSUE THREAD

**Issue by model-123** [trzy/Supermodel#93]
It looks like the spotlight is shining even on the background.

Video
https://youtu.be/wl6tCbnLl7M?si=bqP6Wtzk6ZgmPWG-&t=126
https://youtu.be/cFts_hxXepg?si=TJ_37RMT-y6B_RST&t=137

Screenshot
![スクリーンショット 2023-10-23 211844](https://github.com/trzy/Supermodel/assets/109840450/4072227e-bd62-43cf-b7bd-0e13695dc3bd)

State save
[eca.zip](https://github.com/trzy/Supermodel/files/13069947/eca.zip)

Use Google Translation

**Comment by dukeeeey** [comment]
Hi model123, thanks for this :) I will look at it this evening.

**Comment by dukeeeey** [comment]
should be fixed
