### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by unassumingbadger** [trzy/Supermodel#94]
Linux 6.5.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.3-1 (2023-09-13) x86_64 GNU/Linux
GPU info: 4.6 (Compatibility Profile) Mesa 23.2.1-1 (compatability profile)

OpenGL information:

  Vendor                   : Intel
  Renderer                 : Mesa Intel(R) UHD Graphics (TGL GT2)
  Version                  : 4.6 (Compatibility Profile) Mesa 23.2.1-1
  Shading Language Version : 4.60
  Maximum Vertex Array Size: 3000 vertices
  Maximum Texture Size     : 16384 texels
  Maximum Vertex Attributes: 16
  Maximum Vertex Uniforms  : 16384
  Maximum Texture Img Units: 32

[supermodel.log](https://github.com/trzy/Supermodel/files/13
![Sega Rally 2](https://github.com/trzy/Supermodel/assets/51933591/b1c18a6f-ef4e-46fe-b0d3-786a78e37ebd)
07
![Star Wars Trilogy](https://github.com/trzy/Supermodel/assets/51933591/5d9ee9f1-838f-4cf3-9c99-4b427e062ce8)
3997/supermodel.log)
![The Lost World](https://github.com/trzy/Supermodel/assets/51933591/27a45c82-61d3-4e88-affb-43a67a62f073)

The games appear to run normally, but some 3d objects are white.

**Comment by dukeeeey** [comment]
From another poster:

>@dukeeeey The other games looked the same (ie: white tracks on racing games, which is what I tested so far).

> But this is NOT a Supermodel issue: building and installing latest gitlab MESA (23.0 dev currently) the problem does not happen anymore.

> So, if someone comes here with that problem on Intel XE graphics, tell them to build and install latest gitlab MESA :)

**Comment by unassumingbadger** [comment]
> From another poster:
> 
> > @dukeeeey The other games looked the same (ie: white tracks on racing games, which is what I tested so far).
> 
> > But this is NOT a Supermodel issue: building and installing latest gitlab MESA (23.0 dev currently) the problem does not happen anymore.
> 
> > So, if someone comes here with that problem on Intel XE graphics, tell them to build and install latest gitlab MESA :)

Okay thanks for the heads up. I'll go ahead and close this out.

**Comment by dukeeeey** [comment]
from the other post, apparently this bug still exists
but a work around is if you enable quad-rendering

**Comment by dukeeeey** [comment]
try the latest version, this issue should be fixed, also apparently with improved frame rate
regards :)
