### ISSUE TITLE
[Sega Rally 2] Engine sound is missing?

### ISSUE THREAD

**Issue by vanfanel** [trzy/Supermodel#95]
Using the latest GIT code as always, but I can't hear the engine sound.
Is that a known bug? Searched the issues but didn't find anything.
Is there a workaround?

**Comment by gm-matthew** [comment]
You'll need to use the legacy SCSP DSP when playing Sega Rally 2 to hear the engine sounds; you can either type -legacy-scsp when launching Supermodel from a command prompt or alternatively you can add the line "LegacySoundDSP = true" to Supermodel.ini.

**Comment by vanfanel** [comment]
> You'll need to use the legacy SCSP DSP when playing Sega Rally 2 to hear the engine sounds; you can either type -legacy-scsp when launching Supermodel from a command prompt or alternatively you can add the line "LegacySoundDSP = true" to Supermodel.ini.

Ah, thanks! That clears it up, I guess the new audio engine lacks some functionality, since passing `-legacy-scsp` plays the engine sound nicely.
