### ISSUE TITLE
[scud] white and bright light

### ISSUE THREAD

**Issue by model-123** [trzy/Supermodel#96]
[scud] white and bright light
There is a white bright light in the emulator.

Video
https://youtu.be/iFSpmnKcQj0?si=IAmW1Vtvl4nHEtoA&t=387
https://youtu.be/fMdOngI_Yds?si=tzu3VdMHLRYUHe-W&t=21

Screenshot
![スクリーンショット 2023-10-26 230724](https://github.com/trzy/Supermodel/assets/109840450/46083327-85d2-49ef-9659-e30bc27d88b3)

State save
[scud.zip](https://github.com/trzy/Supermodel/files/13178596/scud.zip)

This is a well-known problem for a long time, but I couldn't find it, so I created it.
Use Google Translation

**Comment by dukeeeey** [comment]
i think this is an issue with the line of sight code, which controls in that scene various fogging values
i'll check it out

**Comment by dukeeeey** [comment]
should be fixed
