### ISSUE TITLE
[srally2] object is white or not drawn.

### ISSUE THREAD

**Issue by model-123** [trzy/Supermodel#98]
object is white or maybe it's not drawn.
Note: Difficult to understand as there is no clear video

Video
https://youtu.be/68L4ux27QMA?si=MOs7mWZ4pCX8w79A&t=51
https://youtu.be/V2Q4QETuhZo?si=O8lgfT_Ld99HYtct&t=171

Screenshot
![スクリーンショット 2023-10-27 000246](https://github.com/trzy/Supermodel/assets/109840450/a50837e5-8b00-42a0-aa4b-8d2a0f94ab3e)
![スクリーンショット 2023-10-27 002641](https://github.com/trzy/Supermodel/assets/109840450/218a45f8-f239-4e10-80be-d09dbc394ce9)

State save
[srally2.zip](https://github.com/trzy/Supermodel/files/13179575/srally2.zip)

Use Google Translation

**Comment by dukeeeey** [comment]
as best as i can work out .. they aren't drawn on the original h/w

**Comment by dukeeeey** [comment]
fixed with Matthew's LOD code
