### ISSUE TITLE
[daytona2] and [dayto2pe] Position number animation at the result screen does not scroll from other side of the screen.

### ISSUE THREAD

**Issue by Jitterdoomer** [trzy/Supermodel#99]
https://youtu.be/6fsZ2f-E_fY?feature=shared (4:16)

In Supermodel, the position number starts from the center of the screen and then magically appeared on the corner of the screen. The real hardware starts from the corner of the screen.

**Comment by trzy** [comment]
There was a change made to scrolling logic a few months ago. I wonder if this caused it. Can you go back to a revision one year ago and check whether it was broken there, too?

**Comment by dukeeeey** [comment]
It happened with older versions too apparently
https://www.youtube.com/watch?v=Rk3Aip-jykE&t=999s

**Comment by Jitterdoomer** [comment]
Yep it was there since the very first version of Supermodel.

**Comment by dukeeeey** [comment]
Fixed thanks to gm_matthew :)
